export interface DocChapter {
	title: string;
	content: string[]; // lines to render, empty string = blank line
}

export const DOC_CHAPTERS: DocChapter[] = [
	{
		title: "Overview",
		content: [
			"PICT — Pairwise Independent Combinatorial Testing",
			"",
			"PICT generates test cases that efficiently cover all pairs of",
			"parameter values (pairwise coverage), dramatically reducing the",
			"number of test cases vs. exhaustive combination.",
			"",
			"Workflow in this app:",
			"  1. Model tab  — define parameters and optional constraints",
			"  2. Options tab — set combination order, randomize, case sensitivity",
			"  3. Press [g]  — generate test cases",
			"  4. Results tab — view, then press [s] to save to file",
			"",
			"Why pairwise?",
			"  Studies show most defects are triggered by interactions",
			"  between 2–3 variables. Pairwise testing catches the same",
			"  bugs as exhaustive testing with a fraction of the cases.",
		],
	},
	{
		title: "Parameter Syntax",
		content: [
			"Basic format:",
			"  Name: Value1, Value2, Value3",
			"",
			"Rules:",
			"  - Each parameter on its own line",
			"  - Name and values separated by a colon",
			"  - Values separated by commas",
			"  - Names and values are case-insensitive by default",
			"  - Numeric values are detected automatically",
			"",
			"Examples:",
			"  Platform: Windows, Linux, macOS",
			"  RAM:      1GB, 2GB, 4GB, 8GB",
			"  Debug:    On, Off",
			"",
			"Quoting:",
			"  Use double quotes for values with special characters,",
			"  spaces, or commas:",
			'  Mode: "Read Only", "Read/Write", "Write Only"',
			"",
			"Numeric ranges:",
			"  Order: 1, 2, 3, 10, 100",
			"  PICT treats these as numbers for inequality constraints.",
		],
	},
	{
		title: "Advanced Parameters",
		content: [
			"Aliases — multiple names for the same value:",
			"  Platform: Windows | Win, Linux | Lin, macOS | Mac",
			"  The alias appears in constraints but primary name in output.",
			"",
			"Negative values — mark invalid/error-path values:",
			"  Size: 1GB, 2GB, ~0, ~-1",
			"  Negative values (prefixed ~) appear in only one test case",
			"  each, keeping the test suite focused on valid combos.",
			"",
			"Weighting — bias selection probability:",
			"  Browser: Chrome (10), Firefox (5), IE (1)",
			"  Higher weight = appears in more test cases.",
			"  Useful to emphasize common configurations.",
			"",
			"Value re-use — reference another parameter's values:",
			"  StartPort: 1, 2, 3, 4, 5",
			"  EndPort:   <StartPort>",
			"  EndPort takes the same value set as StartPort.",
			"  Keeps model DRY for symmetric parameters.",
		],
	},
	{
		title: "Sub-Models",
		content: [
			"Sub-models force higher coverage for a subset of parameters.",
			"",
			"Syntax:",
			"  { Param1, Param2, Param3 } @ N",
			"  N = coverage order (default 2 = pairwise)",
			"",
			"Example:",
			"  Platform: Windows, Linux, macOS",
			"  Browser:  Chrome, Firefox, Edge",
			"  Version:  32-bit, 64-bit",
			"",
			"  { Platform, Browser } @ 3",
			"  This ensures all 3-way combinations of Platform+Browser+Version",
			"  are covered while the rest of the model uses pairwise.",
			"",
			"Use cases:",
			"  - Critical parameter groups that need deeper testing",
			"  - Known interaction-heavy subsystems",
			"  - Regulatory compliance requiring N-way coverage",
			"",
			"Effect:",
			"  Increases test case count for the sub-model group only.",
			"  Other parameters use the Combination Order set in the Options tab.",
		],
	},
	{
		title: "Constraints",
		content: [
			"Constraints exclude invalid parameter combinations.",
			"",
			"Syntax:",
			"  IF <condition> THEN <condition> [ELSE <condition>];",
			"  Constraints end with a semicolon.",
			"",
			"Comparison operators:",
			"  =        equal",
			"  <>       not equal",
			"  >        greater than (numeric)",
			"  >=       greater than or equal",
			"  <        less than (numeric)",
			"  <=       less than or equal",
			"  LIKE     wildcard match (* and ?)",
			"  IN       membership: IN {Val1, Val2}",
			"",
			"Logical operators:",
			"  AND, OR, NOT",
			"",
			"Examples:",
			'  IF [OS] = "Windows" THEN [Browser] <> "Safari";',
			"",
			'  IF [RAM] < 4GB THEN [Mode] = "32-bit";',
			"",
			'  IF [Feature] IN {"Beta", "Alpha"} THEN [Build] = "Debug";',
			"",
			"  IF [A] = 1 AND [B] = 2 THEN [C] <> 3;",
			"",
			"Parameter names in constraints must be in square brackets.",
		],
	},
	{
		title: "Options Tab",
		content: [
			"── PICT Options ─────────────────────────────────────",
			"",
			"Combination Order  1–6, default 2 (pairwise)",
			"  Controls how many parameters must appear together in",
			"  every test case. Higher = more coverage, more cases.",
			"",
			"Randomize          toggle On/Off",
			"  Randomizes test case order on each generation run.",
			"",
			"Case Sensitive     toggle On/Off",
			"  When On, parameter names and values are case-sensitive.",
			"",
			"── Output Configuration ─────────────────────────────",
			"",
			"Output file path   where [s] saves the generated test cases",
			"",
			"Format             TXT / CSV / JSON / XLSX",
			"  Press Enter to cycle through formats.",
			"",
			"── Model Storage ────────────────────────────────────",
			"",
			"Storage path       directory where [w] writes model files",
			"",
			"File template      filename pattern; {timestamp} is replaced",
			"  with the current date-time on each save.",
			"",
			"── AI Settings ──────────────────────────────────────",
			"",
			"AI Model           Haiku 4.5 / Sonnet 4.6 / Opus 4.6",
			"  The Claude model used for AI parameter generation.",
			"  Press Enter to cycle. Persisted across sessions.",
			"",
			"── Navigation ───────────────────────────────────────",
			"",
			"  [Tab]  cycle between fields",
			"  [Esc]  unfocus current field",
		],
	},
	{
		title: "Results & Output",
		content: [
			"After pressing [g] to generate, the Results tab opens",
			"automatically. Columns = parameters, rows = test cases.",
			"",
			"── Saving test cases ────────────────────────────────",
			"",
			"  [s]  Save test cases to the output file.",
			"       Path and format are set in the Options tab.",
			"       Supported formats: TXT, CSV, JSON, XLSX.",
			"",
			"── Model files ──────────────────────────────────────",
			"",
			"  [w]  Write the current model to a .txt file.",
			"       Saved to the storage path using the file template",
			"       (both configured in the Options tab).",
			"",
			"  [o]  Open a saved model file via the file picker.",
			"       Loads parameters and constraints into the Model tab.",
		],
	},
	{
		title: "Examples",
		content: [
			"── Storage Volume Model ──────────────────────────────",
			"",
			"  Type:        Single, Spanned, Striped, Mirror, RAID-5",
			"  FormatMethod: Quick, Slow",
			"  FileSystem:  FAT, FAT32, NTFS",
			"  ClusterSize: 512, 1024, 2048, 4096, 8192, 16384",
			"  Compression: On, Off",
			"",
			'  IF [FileSystem] <> "NTFS" THEN [Compression] = "Off";',
			'  IF [Type] IN {"Spanned","Striped","Mirror","RAID-5"}',
			'     THEN [FormatMethod] = "Quick";',
			"",
			"── Machine Config with Sub-Model ────────────────────",
			"",
			"  CPU:    x86, x64, ARM",
			"  OS:     Win7, Win8, Win10, WinServer",
			"  Memory: 1GB, 4GB, 16GB",
			"  HDD:    SATA, SSD, NVMe",
			"",
			"  { CPU, OS } @ 3",
			"",
			'  IF [CPU] = "ARM" THEN [OS] <> "Win7";',
			"",
			"── Negative Testing ──────────────────────────────────",
			"",
			'  UserName: valid_user, ~null, ~"user with spaces"',
			'  Password: valid_pw,   ~null, ~""',
			"  Role:     Admin, User, Guest",
			"",
			"  Negative values appear exactly once, testing error paths.",
		],
	},
	{
		title: "AI Parameter Fill",
		content: [
			"AI Parameter Fill — generate parameters from a description",
			"",
			"── Setup ────────────────────────────────────────────────",
			"",
			"  Press [i] when no API key is configured, or press [c] inside",
			"  the AI prompt overlay to open the setup screen.",
			"  Enter your Anthropic API key from console.anthropic.com.",
			"  Pro and Max plan subscribers have API access included.",
			"  The key is saved to ~/.config/pairwise-tui/credentials.json",
			"  (0600 permissions) and never logged or transmitted elsewhere.",
			"",
			"  Alternatively, set the ANTHROPIC_API_KEY environment variable",
			"  before launching the app — no setup step needed.",
			"",
			"── Usage ────────────────────────────────────────────────",
			"",
			"  1. Press [i] to open the AI prompt overlay.",
			"  2. Type or paste a description of the feature to test.",
			"     Example: 'Login form with email, password, remember me",
			"     checkbox, and SSO. Browsers: Chrome, Firefox, Safari.'",
			"  3. Press Ctrl+G — Claude extracts parameter names and values.",
			"  4. The Model tab is populated with the generated parameters.",
			"  5. Verify and edit as needed, then press [g] to generate.",
			"",
			"── Model Selection ──────────────────────────────────────",
			"",
			"  The Claude model used for AI fill is configurable in the",
			"  Options tab under 'AI Settings'. Tab to the AI Model field",
			"  and press [Enter] to cycle through available models:",
			"",
			"  Haiku 4.5   — fastest and most cost-effective (default)",
			"  Sonnet 4.6  — balanced speed and intelligence",
			"  Opus 4.6    — most capable, best for complex scenarios",
			"",
			"  The selected model is persisted across sessions.",
			"",
			"── Notes ────────────────────────────────────────────────",
			"",
			"  - Existing parameters are replaced when AI fill runs.",
			"  - Only parameters and values are generated (not constraints).",
		],
	},
];
