export interface DocChapter {
	title: string;
	content: string[]; // lines to render, empty string = blank line
}

export const DOC_CHAPTERS: DocChapter[] = [
	{
		title: "Overview",
		content: [
			"PICT — Pairwise Independent Combinatorial Testing",
			"",
			"PICT generates test cases that efficiently cover all pairs of",
			"parameter values (pairwise coverage), dramatically reducing the",
			"number of test cases vs. exhaustive combination.",
			"",
			"Basic usage:",
			"  pict model.txt",
			"  pict model.txt /o:3 > output.tsv",
			"",
			"A model file defines parameters and optional constraints.",
			"PICT outputs a tab-separated table: one row per test case,",
			"one column per parameter.",
			"",
			"Why pairwise?",
			"  Studies show most defects are triggered by interactions",
			"  between 2–3 variables. Pairwise testing catches the same",
			"  bugs as exhaustive testing with a fraction of the cases.",
		],
	},
	{
		title: "Parameter Syntax",
		content: [
			"Basic format:",
			"  Name: Value1, Value2, Value3",
			"",
			"Rules:",
			"  - Each parameter on its own line",
			"  - Name and values separated by a colon",
			"  - Values separated by commas",
			"  - Names and values are case-insensitive by default",
			"  - Numeric values are detected automatically",
			"",
			"Examples:",
			"  Platform: Windows, Linux, macOS",
			"  RAM:      1GB, 2GB, 4GB, 8GB",
			"  Debug:    On, Off",
			"",
			"Quoting:",
			"  Use double quotes for values with special characters,",
			"  spaces, or commas:",
			'  Mode: "Read Only", "Read/Write", "Write Only"',
			"",
			"Numeric ranges:",
			"  Order: 1, 2, 3, 10, 100",
			"  PICT treats these as numbers for inequality constraints.",
		],
	},
	{
		title: "Advanced Parameters",
		content: [
			"Aliases — multiple names for the same value:",
			"  Platform: Windows | Win, Linux | Lin, macOS | Mac",
			"  The alias appears in constraints but primary name in output.",
			"",
			"Negative values — mark invalid/error-path values:",
			"  Size: 1GB, 2GB, ~0, ~-1",
			"  Negative values (prefixed ~) appear in only one test case",
			"  each, keeping the test suite focused on valid combos.",
			"",
			"Weighting — bias selection probability:",
			"  Browser: Chrome (10), Firefox (5), IE (1)",
			"  Higher weight = appears in more test cases.",
			"  Useful to emphasize common configurations.",
			"",
			"Value re-use — reference another parameter's values:",
			"  StartPort: 1, 2, 3, 4, 5",
			"  EndPort:   <StartPort>",
			"  EndPort takes the same value set as StartPort.",
			"  Keeps model DRY for symmetric parameters.",
		],
	},
	{
		title: "Sub-Models",
		content: [
			"Sub-models force higher coverage for a subset of parameters.",
			"",
			"Syntax:",
			"  { Param1, Param2, Param3 } @ N",
			"  N = coverage order (default 2 = pairwise)",
			"",
			"Example:",
			"  Platform: Windows, Linux, macOS",
			"  Browser:  Chrome, Firefox, Edge",
			"  Version:  32-bit, 64-bit",
			"",
			"  { Platform, Browser } @ 3",
			"  This ensures all 3-way combinations of Platform+Browser+Version",
			"  are covered while the rest of the model uses pairwise.",
			"",
			"Use cases:",
			"  - Critical parameter groups that need deeper testing",
			"  - Known interaction-heavy subsystems",
			"  - Regulatory compliance requiring N-way coverage",
			"",
			"Effect:",
			"  Increases test case count for the sub-model group only.",
			"  The global /o option still governs other parameters.",
		],
	},
	{
		title: "Constraints",
		content: [
			"Constraints exclude invalid parameter combinations.",
			"",
			"Syntax:",
			"  IF <condition> THEN <condition> [ELSE <condition>];",
			"  Constraints end with a semicolon.",
			"",
			"Comparison operators:",
			"  =        equal",
			"  <>       not equal",
			"  >        greater than (numeric)",
			"  >=       greater than or equal",
			"  <        less than (numeric)",
			"  <=       less than or equal",
			"  LIKE     wildcard match (* and ?)",
			"  IN       membership: IN {Val1, Val2}",
			"",
			"Logical operators:",
			"  AND, OR, NOT",
			"",
			"Examples:",
			'  IF [OS] = "Windows" THEN [Browser] <> "Safari";',
			"",
			'  IF [RAM] < 4GB THEN [Mode] = "32-bit";',
			"",
			'  IF [Feature] IN {"Beta", "Alpha"} THEN [Build] = "Debug";',
			"",
			"  IF [A] = 1 AND [B] = 2 THEN [C] <> 3;",
			"",
			"Parameter names in constraints must be in square brackets.",
		],
	},
	{
		title: "Command-Line Options",
		content: [
			"Usage: pict <model> [options]",
			"",
			"/o:N     Coverage order (default 2 = pairwise)",
			"         /o:3 = all 3-way combinations covered",
			"",
			"/d:C     Value delimiter in output (default: tab)",
			'         /d:"," for CSV output',
			"",
			"/a:C     Alias separator (default: |)",
			"",
			"/n:C     Negative value prefix (default: ~)",
			"",
			"/e:file  Seed file — use previous output to extend coverage",
			"",
			"/r[:N]   Randomize generation; N = random seed",
			"         /r        random seed each run",
			"         /r:42     reproducible with seed 42",
			"",
			"/c       Case-sensitive parameter names and values",
			"",
			"/s       Show model statistics only (no test cases)",
			"",
			"Examples:",
			"  pict model.txt /o:3 /r:1234 > cases.tsv",
			"  pict model.txt /c /s",
		],
	},
	{
		title: "Output Format",
		content: [
			"Default output: tab-separated values (TSV)",
			"  - First row: parameter names (header)",
			"  - Each subsequent row: one test case",
			"",
			"Redirect to file:",
			"  pict model.txt > output.tsv",
			"",
			"CSV output:",
			'  pict model.txt /d:"," > output.csv',
			"",
			"Example output (3 parameters, 4 test cases):",
			"  OS        Browser  RAM",
			"  Windows   Chrome   4GB",
			"  Linux     Firefox  2GB",
			"  macOS     Chrome   2GB",
			"  Windows   Firefox  4GB",
			"",
			"Statistics mode (/s):",
			"  Shows parameter count, value count, and estimated",
			"  test case count without generating output.",
			"",
			"Exit codes:",
			"  0  Success",
			"  1  Model or constraint error",
		],
	},
	{
		title: "Examples",
		content: [
			"── Storage Volume Model ──────────────────────────────",
			"",
			"  Type:        Single, Spanned, Striped, Mirror, RAID-5",
			"  FormatMethod: Quick, Slow",
			"  FileSystem:  FAT, FAT32, NTFS",
			"  ClusterSize: 512, 1024, 2048, 4096, 8192, 16384",
			"  Compression: On, Off",
			"",
			'  IF [FileSystem] <> "NTFS" THEN [Compression] = "Off";',
			'  IF [Type] IN {"Spanned","Striped","Mirror","RAID-5"}',
			'     THEN [FormatMethod] = "Quick";',
			"",
			"── Machine Config with Sub-Model ────────────────────",
			"",
			"  CPU:    x86, x64, ARM",
			"  OS:     Win7, Win8, Win10, WinServer",
			"  Memory: 1GB, 4GB, 16GB",
			"  HDD:    SATA, SSD, NVMe",
			"",
			"  { CPU, OS } @ 3",
			"",
			'  IF [CPU] = "ARM" THEN [OS] <> "Win7";',
			"",
			"── Negative Testing ──────────────────────────────────",
			"",
			'  UserName: valid_user, ~null, ~"user with spaces"',
			'  Password: valid_pw,   ~null, ~""',
			"  Role:     Admin, User, Guest",
			"",
			"  Negative values appear exactly once, testing error paths.",
		],
	},
];
